// Copyright (c) 2025 Open Swarm Contributors
//
// This software is released under the MIT License.
// See LICENSE file in the repository for details.

package temporal

import (
	"fmt"

	"go.temporal.io/sdk/log"
	"go.temporal.io/sdk/workflow"
)

// gateExecutor executes a gate activity and handles common error/duration tracking
type gateExecutor struct {
	ctx            workflow.Context
	logger         log.Logger
	result         *EnhancedTCRResult
	bootstrap      *BootstrapOutput
	cellActivities *CellActivities
}

// executeGate runs a gate activity and handles result tracking
func (ge *gateExecutor) executeGate(gateName string, activityFn interface{}, args ...interface{}) error {
	ge.logger.Info(fmt.Sprintf("Gate: %s", gateName))
	gateStart := workflow.Now(ge.ctx)

	var gateResult *GateResult
	err := workflow.ExecuteActivity(ge.ctx, activityFn, args...).Get(ge.ctx, &gateResult)

	if err != nil {
		gateResult = &GateResult{
			GateName: gateName,
			Passed:   false,
			Error:    err.Error(),
			Duration: workflow.Now(ge.ctx).Sub(gateStart),
		}
	} else {
		gateResult.Duration = workflow.Now(ge.ctx).Sub(gateStart)
	}

	ge.result.GateResults = append(ge.result.GateResults, *gateResult)

	if !gateResult.Passed {
		ge.result.Error = fmt.Sprintf("%s failed: %v", gateName, gateResult.Error)
		// Revert changes on gate failure
		_ = workflow.ExecuteActivity(ge.ctx, ge.cellActivities.RevertChanges, ge.bootstrap).Get(ge.ctx, nil)
		return fmt.Errorf("gate failed")
	}

	// Track files changed if available
	if len(gateResult.AgentResults) > 0 {
		for _, agentResult := range gateResult.AgentResults {
			ge.result.FilesChanged = append(ge.result.FilesChanged, agentResult.FilesChanged...)
		}
	}

	return nil
}

// EnhancedTCRWorkflow implements the 6-Gate Enhanced TCR pattern with file locks
// Flow: Bootstrap → AcquireLocks → [GenTest → LintTest → VerifyRED → GenImpl → VerifyGREEN → MultiReview] → Commit/Revert → ReleaseLocks → Teardown
//
// Uses saga pattern to guarantee lock release even on failure.
// All gates must pass sequentially; failure triggers revert and retry signal.
func EnhancedTCRWorkflow(ctx workflow.Context, input EnhancedTCRInput) (*EnhancedTCRResult, error) {
	logger := workflow.GetLogger(ctx)
	logger.Info("Starting Enhanced TCR Workflow", "taskID", input.TaskID)

	// Initialize result
	result := &EnhancedTCRResult{
		Success:      false,
		GateResults:  []GateResult{},
		FilesChanged: []string{},
		Error:        "",
	}

	// Activity options - use shared non-idempotent options
	ctx = WithNonIdempotentOptions(ctx)

	cellActivities := NewCellActivities()
	enhancedActivities := NewEnhancedActivities()

	// STEP 1: Bootstrap Cell
	logger.Info("Gate: Bootstrap")
	var bootstrap *BootstrapOutput
	err := workflow.ExecuteActivity(ctx, cellActivities.BootstrapCell, BootstrapInput{
		CellID: input.CellID,
		Branch: input.Branch,
	}).Get(ctx, &bootstrap)

	if err != nil {
		result.Error = fmt.Sprintf("bootstrap failed: %v", err)
		return result, nil
	}

	// SAGA PATTERN: Ensure cleanup happens (teardown + lock release)
	var locksAcquired []string
	defer func() {
		sagaCtx, _ := NewSagaContext(ctx)

		// Release all acquired locks
		if len(locksAcquired) > 0 {
			logger.Info("Saga: Releasing file locks", "count", len(locksAcquired))
			_ = workflow.ExecuteActivity(sagaCtx, enhancedActivities.ReleaseFileLocks,
				input.CellID, locksAcquired).Get(sagaCtx, nil)
		}

		// Teardown cell
		logger.Info("Saga: Tearing down cell", "cellID", bootstrap.CellID)
		_ = workflow.ExecuteActivity(sagaCtx, cellActivities.TeardownCell, bootstrap).Get(sagaCtx, nil)
	}()

	// STEP 2: Acquire File Locks
	logger.Info("Acquiring file locks for task files")
	var filesLocked []string
	err = workflow.ExecuteActivity(ctx, enhancedActivities.AcquireFileLocks,
		input.CellID, input.TaskID).Get(ctx, &filesLocked)

	if err != nil {
		result.Error = fmt.Sprintf("failed to acquire locks: %v", err)
		return result, nil
	}
	locksAcquired = filesLocked
	logger.Info("File locks acquired", "files", filesLocked)

	// Create gate executor for simplified gate execution
	executor := &gateExecutor{
		ctx:            ctx,
		logger:         logger,
		result:         result,
		bootstrap:      bootstrap,
		cellActivities: cellActivities,
	}

	// Execute all gates in sequence
	if err := executeEnhancedTCRGates(executor, enhancedActivities, bootstrap, input); err != nil {
		return result, nil
	}

	// ALL GATES PASSED: Commit Changes
	logger.Info("All gates passed - committing changes")

	commitMsg := fmt.Sprintf("Task %s: %s\n\nEnhanced TCR - All 6 gates passed\n\nGenerated by Open Swarm", input.TaskID, input.Description)
	err = workflow.ExecuteActivity(ctx, cellActivities.CommitChanges, bootstrap, commitMsg).Get(ctx, nil)
	if err != nil {
		logger.Warn("Commit failed", "error", err)
		result.Error = fmt.Sprintf("commit failed: %v", err)
		return result, nil
	}

	// Success!
	result.Success = true
	logger.Info("Enhanced TCR Workflow completed successfully", "taskID", input.TaskID)

	return result, nil
}

// executeEnhancedTCRGates executes all 6 gates of the Enhanced TCR workflow in sequence
func executeEnhancedTCRGates(executor *gateExecutor, enhancedActivities *EnhancedActivities, bootstrap *BootstrapOutput, input EnhancedTCRInput) error {
	// GATE 1: GenTest - Generate Tests
	if err := executor.executeGate("GenTest", enhancedActivities.ExecuteGenTest,
		bootstrap, input.TaskID, input.AcceptanceCriteria); err != nil {
		return err
	}

	// GATE 2: LintTest - Lint Test Files
	if err := executor.executeGate("LintTest", enhancedActivities.ExecuteLintTest, bootstrap); err != nil {
		return err
	}

	// GATE 3: VerifyRED - Tests Must Fail
	if err := executor.executeGate("VerifyRED", enhancedActivities.ExecuteVerifyRED, bootstrap, input.TaskID); err != nil {
		return err
	}

	// GATE 4: GenImpl - Generate Implementation
	if err := executor.executeGate("GenImpl", enhancedActivities.ExecuteGenImpl,
		bootstrap, input.TaskID, input.Description, input.AcceptanceCriteria, ""); err != nil {
		return err
	}

	// GATE 5: VerifyGREEN - Tests Must Pass
	if err := executor.executeGate("VerifyGREEN", enhancedActivities.ExecuteVerifyGREEN, bootstrap, input.TaskID); err != nil {
		return err
	}

	// GATE 6: MultiReview - 3 Reviewers with Unanimous Approval
	reviewersCount := input.ReviewersCount
	if reviewersCount == 0 {
		reviewersCount = 3 // Default: 3 reviewers
	}

	return executor.executeGate("MultiReview", enhancedActivities.ExecuteMultiReview,
		bootstrap, input.TaskID, input.Description, reviewersCount)
}
